version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_development:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  postgres_data_development: